spp-master/config/routes.rb
Rails.application.routes.draw do
  root 'react#index'
  #Added v0 prefix to all rails routes
  #Rails routes blocking offline saving if no prefix
  scope :v0 do

    get "/blog" => "blog_posts#index", as: :v0_blog_posts
    post "/blog" => "blog_posts#create", as: :v0_create_blog_post
    get '/blog/search', to: 'blog_posts#search', as: :v0_blog_search
    get '/blog/dashboard', to: 'blog_posts#dashboard', as: :v0_blog_dashboard
    get '/blog/drafts', to: 'blog_posts#drafts', as: :v0_blog_drafts
    get '/blog/scheduled_posts', to: 'blog_posts#scheduled_posts', as: :v0_blog_scheduled_posts
    get '/blog/de_activated', to: 'blog_posts#de_activated', as: :v0_blog_de_activated
    get '/blog/new_comments', to: 'blog_posts#new_comments', as: :v0_new_comments
    resources :blog_posts,  except: [:create, :index] do
      get :autocomplete_tag_name, :on => :collection
      resources :comments, only: [:create, :destroy]
    end

    # devise_for :users
    #devise_for :users, :skip=>[:omniauth_callbacks, :sessions], :controllers => { :registrations => 'registrations'}
    post '/stories/update_story_read', to: 'stories#update_story_read', as: :update_story_read
    post '/stories/show_selected_stories', to: 'stories#show_selected_stories', as: :show_selected_stories

    get '/lists/:id/download', to: "api/v1/lists#download", as: :list_download

    resources 'illustrations' do
      get :autocomplete_user_email, :on => :collection
      get :autocomplete_tag_name, :on => :collection
    end

    #Organization_routes
    get '/organizations/organization_sign_up_model', to: 'organizations#organization_sign_up_model', as: :organization_sign_up_model
    post '/organizations/organization_sign_up', to: 'organizations#organization_sign_up', as: :organization_sign_up
    get '/organizations/new_users', to: 'organizations#new_users', as: :new_users
    get '/organizations/organizations_list', to: 'organizations#organizations_list', as: :organizations_list
    get 'organizations/assign_org_role', to: 'organizations#assign_org_role', as: :assign_org_role
    get '/organizations/check_org_publisher', to: 'organizations#check_org_publisher', as: :check_org_publisher
    post '/organizations/add_org_logo', to: 'organizations#add_org_logo', as: :add_org_logo
    #get '/organizations/remove_site_role', to: 'organizations#remove_site_role', as: :remove_site_role
    get '/organizations/validate_org_name_country', to: 'organizations#validate_org_name_country', as: :validate_org_name_country
    get '/organizations/autocomplete', to: 'organizations#autocomplete', as: :organizations_autocomplete
    get 'organizations/remove_org_role_dialog', to: 'organizations#remove_org_role_dialog', as: :remove_org_role_dialog
    get 'organizations/remove_org_role', to: 'organizations#remove_org_role', as: :remove_org_role

    get '/illustrations/:id/new_flag_illustration', to: 'illustrations#new_flag_illustration' , as: :new_flag_illustration
    post '/illustrations/flag_illustration/:id', to: 'illustrations#flag_illustration' , as: :flag_illustration

    get '/illustrations/download/:id', to: 'illustrations#download', as: :download_illustrations
    get '/illustration-view/:id', to: 'illustrations#illustration_view', as: :view_illustration
    post '/illustrations/update_favorites', to: 'illustrations#update_favorites', as: :update_favorites

    get '/stories/bulk_download', to: 'stories#bulk_download', as: :bulk_download
    #get '/stories/show_selected_stories', to: 'stories#show_selected_stories', as: :show_selected_stories

    resources 'stories',  except: [:show, :index] do
      resources 'pages' do
        get 'epub'
      end
      resources 'translations'
      resources 'relevels'
      member do
        patch 'publish'
        post 'create_post'
      end
      get :autocomplete_tag_name, :on => :collection
    end
    get 'profile/change_translator' => 'profile#change_translator', as: :profile_change_translator

    get "/stories/new_story_from_illustration/:id", to: "stories#new_story_from_illustration", as: :new_story_from_illustration
    get "/stories/create_story_from_illustration", to: "stories#create_story_from_illustration", as: :create_story_from_illustration
    get '/stories/:id/editable', to: 'stories#editable' , as: :story_editor_editable
    post '/stories/reviewer_rating_comment', to: 'stories#reviewer_rating_comment', as: :reviewer_rating_comment
    get '/stories/edit_story_editor/:id', to: 'stories#edit_story_editor', as: :edit_story_editor
    patch '/stories/:id/assign_change_editor', to: 'stories#assign_change_editor', as: :assign_change_editor
    get '/stories/close_assign_dailog/:id', to: 'stories#close_assign_dailog', as: :close_assign_dailog
    get '/stories/:id/new_flag_story', to: 'stories#new_flag_story' , as: :new_flag_story
    post '/stories/flag_story/:id', to: 'stories#flag_story' , as: :flag_story
    post "/stories/recommend_story_on_home", to: "stories#recommend_story_on_home", as: :recommend_story_on_home
    get '/stories/download-story/:id', to: 'stories#download_story', as: :download_story


    get 'stories/show-in-iframe/:id', to: 'stories#show_in_iframe', as: :v0_show_story_in_iframe
    get "/start" , to: 'home#index', as: :start_new_story
    get "/translate_suggestions" , to: 'stories#translate_suggestions' , as: :stories_translate_suggestions
    get 'stories/:id/story-review', to: 'stories#story_review', as: :story_review
    post 'stories/:id/reviewer-comments', to: "stories#reviewer_comments", as: :reviewer_comments
    get 'stories/review_next_story/:id', to: "stories#review_next_story", as: :review_next_story
    resources 'illustration_crops'

    # editor routes
    patch '/editor/:id/update_dummy_draft', to: "story_editor#update_dummy_draft", as: :update_dummy_draft
    get '/editor/story/user_email', to: 'story_editor#get_email', as: :story_editor_get_email
    get '/editor/story/:id', to: 'story_editor#story' , as: :story_editor
    get '/editor/illustration/:id', to: 'story_editor#illustration_for_crop' , as: :illustration_for_crop, :defaults => { :format => :json }
    post '/editor/:page_id/crop/:id', to: 'story_editor#crop_illustration' , as: :crop_illustration
    get '/editor/page/:id', to: 'story_editor#page_edit' , as: :page_edit
    put '/editor/page/:page_id/change_template/:id', to: 'story_editor#change_page_template' , as: :change_template
    put '/editor/story/:story_id/insert/:id', to: 'story_editor#insert_page' , as: :insert_page
    put '/editor/story/:story_id/duplicate/:id', to: 'story_editor#duplicate_page' , as: :duplicate_page
    delete '/editor/story/:story_id/delete/:id', to: 'story_editor#delete_page' , as: :delete_page
    post '/editor/page/:id/illustration', to: 'story_editor#update_page_illustration', as: :update_page_illustration
    get '/editor/page/:id/illustration', to: 'story_editor#remove_page_illustration', as: :remove_page_illustration
    post '/editor/page/:id/content', to: 'story_editor#update_page_content', as: :update_page_content
    post '/editor/page/:id/auto_save_content', to: 'story_editor#auto_save_content', as: :auto_save_content
    post '/editor/page/:id/save_content_on_blur', to: 'story_editor#save_content_on_blur', as: :save_content_on_blur
    post '/editor/story/:id/rearrange', to: 'story_editor#rearrange_page', as: :rearrange_page
    get '/editor/search/illustration', to: 'story_editor#search_illustration', as: :search_illustration
    get '/editor/new_illustration', to: 'story_editor#new_illustration', as: :editor_new_illustration
    post '/editor/create_illustration', to: 'story_editor#create_illustration', as: :editor_create_illustration
    get '/editor/story/:id/validate_pages', to: 'story_editor#validate_story_pages', as: :editor_validate_story_pages
    get '/editor/story/:id/publish', to: 'story_editor#publish_form', as: :editor_publish_story_form
    get '/editor/story/:id/edit_book_info', to: 'story_editor#edit_book_info', as: :editor_edit_book_info
    patch '/editor/story/:id/publish', to: 'story_editor#publish', as: :editor_publish_story
    patch '/editor/story/:id/update', to: 'story_editor#update', as: :editor_update_story
    patch '/editor/story/:id/update_book_info', to: 'story_editor#update_book_info', as: :editor_update_book_info
    get '/editor/autocomplete_user_email', to: 'story_editor#autocomplete_user_email', as: :autocomplete_user_email_path
    get '/editor/save_to_draft', to: 'story_editor#save_to_draft', as: :save_to_draft
    get '/editor/get-all-illustrations', to: 'story_editor#get_all_illustrations', as: :get_all_illustrations
    get '/editor/get-favourite-illustrations', to: 'story_editor#get_favourite_illustrations', as: :get_favourite_illustrations
    get '/editor/upload-illustration', to: 'story_editor#upload_illustration', as: :upload_illustration
    get '/editor/language_script', to: "story_editor#language_script", as: :story_language_script
    get "/editor/create", to: "stories#create_story", as: :create_story
    get "/editor/:story_id/translate", to: "translations#translate_story", as: :translate_story
    get "/editor/:story_id/relevel", to: "relevels#relevel_story", as: :relevel_story

    # illustration tags
    get '/illustration/edit-tags/:id', to: 'illustrations#edit_tags', as: :edit_illustration_tags
    patch '/illustration/:id/update-tags', to: 'illustrations#update_tags', as: :update_illustration_tags
    get 'illustration/:id/used_stories', to: 'illustrations#illustration_used_in_stories', as: :illustration_used_in_stories
    #contest routes
    get 'contests/:id/contest_winners_details', to: 'contests#contest_winners_details', as: :contest_winners_details
    resources :contests
    get '/contests/:id/details', to: 'contests#contest_details', as: :contest_details
    #contest_illustrations
    post '/illustrations/contest_image', to: 'illustrations#contest_image', as: :contest_image

spp-master/app/views/layouts/_bookends_data.html.erb
<script>
    <% locale = session[:user_locale] ? session[:user_locale] : "en" %>
  window.INITIAL_STATE = {
      "user" : {
  <% if current_user %>
        <% profile = current_user.profile %>
        <% profile["locale"] = locale %>
        <% profile["languagePreferences"] = current_user.language_preferences_list %>
        <% profile["readingLevels"] = current_user.reading_levels_list %>
        "isLoggedIn": true,
        "profile" : <%= raw profile.to_json %>,
  <% else %>
        "isLoggedIn": false,
        "profile" : {
          "roles" : [],
          "locale": "<%= locale %>"
         }
  <% end %>
      }
    }
</script>

spp-master/app/views/layouts/_editor_header.html.erb
<header id="header">
  <div class="top-bar">
    <div>
      <div class="row">
        <div class="col-md-12 col-sm-12 menu-nav-but">
          <nav class="navbar navbar-inverse" role="banner">
            <div class="col-md-12 col-sm-12">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
              </div>
              <div class="top-links editor-top-links">
                <%= render 'layouts/navigation_links' %>
              </div>
              <div class="collapse navbar-collapse menu-nav editor-navbar">
                <ul id="menu" class="nav navbar-nav">
                  <%= render :partial => 'layouts/menu', locals: {editor: true} %>
                </ul>
              </div>
            </div>
          </nav>
        </div>
      </div>
    </div>
  </div>
</header>
<script>
  $('.menu-nav-but').addClass('original').clone().insertAfter('.menu-nav-but').addClass('cloned').css('position','fixed').css('top','0').css('margin-top','0').css('z-index','500000').css('background','#fff').removeClass('original').hide();
  scrollIntervalID = setInterval(stickIt, 10);
  function stickIt() {
    if ($(window).width() > 767) {
      var orgElementPos = $('.original').offset();
      orgElementTop = orgElementPos.top;
      if ($(window).scrollTop() >= (orgElementTop)) {
        // scrolled past the original position; now only show the cloned, sticky element.
        // Cloned element should always have same left position and width as original element.
        orgElement = $('.original');
        coordsOrgElement = orgElement.offset();
        leftOrgElement = coordsOrgElement.left;
        widthOrgElement = orgElement.css('width');
        $('.cloned').css('left',leftOrgElement+'px').css('top',0).css('width',widthOrgElement).show();
        $('.original').css('visibility','hidden');
      } else {
        // not scrolled past the menu; only show the original menu.
        $('.cloned').hide();
        $('.original').css('visibility','visible');
      }
    }
  }
  $( document ).ready(function() {
    $(".mobile-icon").click(function(){
      $(".hide-toggle").show();
      $(".close-search").show();
    });
    $(".close-search").click(function(){
      $(".hide-toggle").hide();
      $(".close-search").hide();
    });
    $(".mobile-user-icon").click(function(){
      $(".top-links #navigation_links").slideToggle('slow');
      $(".top-links #test").slideToggle('slow');
    });
    $('#menu a').on('mouseenter focus', function () {
      $('#menu a').removeClass("menu-hover");
      $('#menu a').children("span").removeClass("common-bird-hover");
      $(this).addClass("menu-hover");
      $(this).children("span").addClass("common-bird-hover");
    });

    $('#menu a').on('mouseleave blur', function (){
      $(this).removeClass("menu-hover");
      $(this).children("span").removeClass("common-bird-hover");
    });
  });

</script>

spp-master/app/views/layouts/_fluid.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Browse through thousands of openly licensed stories for children in over 100 languages of the world. FREE to read, download, print and share!" %>">
<title><%= content_for?(:title) ? yield(:title) : "Welcome to Pratham Books' StoryWeaver!".html_safe %></title>

<meta property="og:title" content="<%= content_for?(:fb_title) ? yield(:fb_title) : 'StoryWeaver' %>"/>
<meta property="og:url" content="<%= content_for?(:fb_url) ? yield(:fb_url) : 'https://storyweaver.og.in' %>"/>
<meta property="og:description" content="<%= content_for?(:fb_description) ? yield(:fb_description) : 'StoryWeaver' %>"/>
<meta property="og:image" content="<%= content_for?(:fb_image_url) ? yield(:fb_image_url) : 'https://storyweaver.org.in/assets/pb-storyweaver-logo-01-4acd9848be4ca29481825c4b23848b97.svg' %>"/>


<link rel="shortcut icon" type="image/jpg" href="<%= asset_path("favicon.ico") %>"/>
<link href="https://fonts.googleapis.com/css?family=Bree+Serif|Raleway:400,700" rel="stylesheet">
<%= stylesheet_link_tag 'application', media: 'all' %>
<link href="/assets/css/bookends.2df2039c.css?body=1" media="all" rel="stylesheet" />
<!--[if IE]>
    <%= javascript_include_tag "html5shiv.js" %>
    <%= javascript_include_tag "respond.min.js" %>
    <![endif]-->
<%= javascript_include_tag 'application' %>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.form/3.51/jquery.form.min.js"></script>
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="<%= asset_path("apple_icons/favicon_114x114.png") %>">
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="<%= asset_path("apple_icons/favicon_144x144.png") %>">
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="<%= asset_path("apple_icons/favicon_72x72.png") %>">
<link rel="apple-touch-icon-precomposed" href="<%= asset_path("apple_icons/favicon_57x57.png") %>">
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
<%= csrf_meta_tags %>

<script>
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
			(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', "<%= Settings.analytics.tracking_id %>", 'auto');
	ga('send', 'pageview');
	var dimensionValue = "<%= current_user ? current_user.email : "User" %>";
	ga('set', 'dimension1', dimensionValue);
</script>

<%= render "layouts/bookends_data" %>

</head>
<body>
<div id="header"></div>
<div id="social_container">
  <a href="https://www.facebook.com/pbstoryweaver" target="_blank">
    <label class="facebook"></label>
  </a>
  <a href="https://www.twitter.com/pbstoryweaver" target="_blank">
    <label class="twitter"></label>
  </a>
  <a href="https://www.youtube.com/channel/UCH9_ahl5Vu8P9tElauPWahg" target="_blank">
    <label class="youtube"></label>
  </a>
  <a href="https://storyweaver.org.in/blog" target="_blank">
    <label class="blog"></label>
  </a>
  <a href="https://www.instagram.com/pbstoryweaver" target="_blank">
    <label class="instagram"></label>
  </a>
</div>
<div class="container">
  <%= render 'layouts/messages' unless generating_cover? %>
</div>
<div>
  <%= yield %>
</div>
<div id="footer"></div>
<div id="auth-modal"></div>

</body>
<% unless params[:iframe] %>
  <script src="/assets/js/vendor.e63396d6.js"></script>
  <script src="/assets/js/bookends.b6a66b9b.js"></script>
<% end %>
</html>

spp-master/app/views/layouts/_footer.html.erb
<footer id="footer" class="midnight-blue">
  <div>
  	<div class="row" id="bottom">
      
      <div class="col-md-6 col-sm-6 footer-menu">
        <div class="widget">
          <ul>
            <li><a href="<%= about_path %>">StoryWeaver |</a></li>
            <li><a href="/blog">Blog |</a></li>
            <li><a href="<%= tutorials_path %>">FAQs |</a> </li>
            <li><a href="<%= terms_and_conditions_path %>">T&C  |</a></li>
            <li><a href="<%= contact_path %>">Contact |</a></li>
          </ul>
          <p>
            <a href="/open_content">open licensed content</a> <span>.</span> 
            <a href="/privacy_policy">privacy policy</a> <span>.</span> 
            <a href="/prathambooks">pratham books</a> <span>.</span> 
            <a href="/our_supporters"> credits</a>
          </p>
        </div>    
      </div>
      <div class="col-md-6 col-sm-6 footer-social">
        <div class="widget">
          <div class="social bott-my">
          	<h3>follow us on </h3>
            <ul class="social-share">
            	<li><a href="https://www.facebook.com/pbstoryweaver" target="_blank"><i class="fa fa-facebook"></i></a></li>
            	<li><a href="https://twitter.com/PBStoryWeaver" target="_blank"><i class="fa fa-twitter"></i></a></li>
              <li><a href="https://www.youtube.com/channel/UCH9_ahl5Vu8P9tElauPWahg" target="_blank"><i class="fa fa-youtube-play"></i></a></li>
            	<li><a href="/blog" target="_blank"><i class="fa fa-rss"></i></a></li>
            </ul>
          </div>
        </div>    
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12">
        <p><a href="/privacy_policy">Privacy Policy</a> | <a href="/terms_and_conditions">Terms & Conditions</a> | &copy; 2015 <a class="site-title" target="_blank" href="/prathambooks">Pratham Books.</a> All Rights Reserved.<br />
         Except where otherwise noted, content on this site is licensed under a Creative Commons Attribution 4.0 Licence International (CC-BY-4.0) <a href="http://creativecommons.org/licenses/by/4.0/" target="_blank">http://creativecommons.org/licenses/by/4.0/</a></p>
      </div>
    </div>
  </div>
</footer>
<%= render :partial => 'layouts/signup_popup' %>

<script>
	jQuery('body').bind('click', function(e) {
    if(jQuery(e.target).closest('.navbar').length == 0) {
        // click happened outside of .navbar, so hide
        var opened = jQuery('.navbar-collapse').hasClass('collapse in');
        if ( opened === true ) {
            jQuery('.navbar-collapse').collapse('hide');
        }
    }
});
</script>

spp-master/app/views/layouts/_menu.html.erb
<% if editor %><li><a href="<%= root_path %>" class="<%= @menu == 'home' ? 'active' : '' %>"><span class="common-bird b1"></span>Home</a></li> <% end %>
<li><a href="<%= search_path %>" class="<%= @menu == 'search' ? 'active' : '' %>"><span class="common-bird b1"></span>Read</a></li>
<li><%= link_to "<span class='common-bird b2'></span>Create".html_safe, stories_path, method: :post %></li>
<li><a href="<%= stories_translate_path %>" class="<%= @menu == 'translate' ? 'active' : '' %>"><span class="common-bird b3"></span>Translate</a></li>
<li><a href="<%= illustrations_path %>" class="<%= @menu == 'illustrations' ? 'active' : '' %>"><span class="common-bird b4"></span>Images</a></li>
<li><a href="<%= about_path %>" class="<%= @menu == 'about' ? 'active' : '' %>"><span class="common-bird b5"></span>About</a></li>
<div id="newStoryForm"></div>

spp-master/app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

spp-master/app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse" role="banner">
  <div class="container">
    <div class="col-sm-10 col-xs-6">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

      </div>

      <div class="collapse navbar-collapse menu-nav">
        <ul id="menu" class="nav navbar-nav">
          <%= render 'layouts/menu' %>
        </ul>
      </div>
    </div>
    <div class="col-sm-2 col-xs-6">
      <div class="social top-soc-ico">
        <ul class="social-share">
        	<li><a href="#"><i class="fa fa-facebook"></i></a></li>
          <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
          
        </ul>
      </div>
    </div>
  </div>
</nav>

spp-master/app/views/layouts/_navigation_links.html.erb
<% if user_signed_in? %>
<div id="homepage_dropdown">
    <button class=" btn dropdown-toggle profile-dropdown"  type="button" data-toggle="dropdown"><%= link_to current_user.first_name %>
    <span class="caret"></span></button>
        <ul class="dropdown-menu  profile-links" id="test" >
          <li class="display_user">
            <%= current_user.first_name %>
          </li>
          <li class="dash-line">
            <%= link_to "Profile", profile_path if current_user && !current_user.admin? %>
          </li>
          <li class="menu-upload" >
            <%= link_to "Dashboard", dashboard_path if current_user && current_user.content_manager? %>
          </li>
          <li class="menu-upload" >
            <%= link_to "Contest Dashboard", contests_path if current_user && (current_user.promotion_manager? || current_user.content_manager?) %>
          </li>
          <li class="menu-upload" >
            <%= link_to "Blog Dashboard", blog_dashboard_path if current_user && (current_user.promotion_manager? || current_user.content_manager?) %>
          </li>
          <li class="menu-upload" >
            <%= link_to "Rating Dashboard" , reviewed_stroies_path  if current_user && current_user.content_manager? %>
          </li>
          <li class="menu-upload" >
            <%= link_to "Translation Dashboard" , un_translated_stories_path  if current_user && current_user.content_manager? %>
          </li>

          <li class="menu-upload" >
            <%= link_to "Analytics" , analytics_path  if current_user && (current_user.content_manager? || current_user.outreach_manager?) %>
          </li>
          <li>
            <%= link_to "Rate a Story", reviewer_un_reviewed_stories_path if current_user && current_user.languages.any?  %>
          </li>
          <li>
            <%=  link_to "Translate a Story", translator_un_translated_stories_path if current_user && current_user.tlanguages.any? %>
          </li>
          <li>
            <%= link_to "Sign Out", destroy_user_session_path , :method => :delete %>
          </li>
        </ul>
</div>
<% else %>
  <% if (ENV['FACEBOOK_AUTH']||"false")=="true" %>
  <li class="loginLinks">
   <div class="modal fade login-form" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="moreLinksModalLabel" aria-hidden="true">
     <div class="modal-dialog">
       <div class="modal-content">
         <div class="modal-body">  
         <div class="login-top">
            <h3>Login</h3>
            <button id="Register" class="btn btn-primary reg-btn">New? Join Story Weaver...</button>
            </div>      	
	          <%= render "devise/sessions/form"  %>
            <div class="modal-footer">
         
           </div>
        </div>
       </div>
     </div>
   </div>
<a class="btn btn-primary btn-lg sign-inbtn-mobile" data-toggle="modal" data-target="#loginModal"><i class="fa fa-user"></i></a>
<a class="btn btn-primary btn-lg sign-inbtn" data-toggle="modal" data-target="#loginModal">Log in</a><span class="sig-slash"> | </span>
<a class="btn btn-primary btn-lg sign-inbtn" data-toggle="modal" data-target="#registerModal">Sign up</a>
    <div class="modal fade login-form" id="registerModal" tabindex="-1" role="dialog" aria-labelledby="moreLinksModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">         
         <div class="modal-body">
            <div class="login-top">
              <h3>Sign up</h3>
              <button id="Login" class="btn btn-primary log-btn">Already have a password? Log in</button>
            </div>
              <%= render "devise/registrations/form" %>
	            <div class="modal-footer">
	            </div>
           </div>
         </div>
       </div>
    </div>
  </li>
<% else %>
<div id="navigation_links" class="nav navbar-nav pull-right login_signup_link">
   <li class="dash-line"> <%= link_to "Log In", new_user_session_path %></li>
  <li>
    <%= link_to "Sign Up", new_user_registration_path %>
  </li>
</div>
<% end %>

<% end %>
<script>
$('#Login').click(function() {	
	$('#registerModal').modal('hide');
	//Needed to ensure login modal opens only after closing registration modal
	setTimeout(function(){
    	$('#loginModal').modal('show');
    }, 400);
});
$('#Register').click(function() {
	$('#loginModal').modal('hide');
	setTimeout(function(){
    	$('#registerModal').modal('show');
	}, 400);
});
</script>

spp-master/app/views/layouts/contents.html.erb
<%= render 'layouts/fluid' %>

spp-master/app/views/layouts/home.html.erb
<%= render 'layouts/fluid' %>

spp-master/app/views/layouts/react.html.erb
<%= render "layouts/bookends_data" %>
<%= yield %>