spp-master/config/routes.rb
Rails.application.routes.draw do
  root 'react#index'
  #Added v0 prefix to all rails routes
  #Rails routes blocking offline saving if no prefix
  scope :v0 do

    get "/blog" => "blog_posts#index", as: :v0_blog_posts
    post "/blog" => "blog_posts#create", as: :v0_create_blog_post
    get '/blog/search', to: 'blog_posts#search', as: :v0_blog_search
    get '/blog/dashboard', to: 'blog_posts#dashboard', as: :v0_blog_dashboard
    get '/blog/drafts', to: 'blog_posts#drafts', as: :v0_blog_drafts
    get '/blog/scheduled_posts', to: 'blog_posts#scheduled_posts', as: :v0_blog_scheduled_posts
    get '/blog/de_activated', to: 'blog_posts#de_activated', as: :v0_blog_de_activated
    get '/blog/new_comments', to: 'blog_posts#new_comments', as: :v0_new_comments
    resources :blog_posts,  except: [:create, :index] do
      get :autocomplete_tag_name, :on => :collection
      resources :comments, only: [:create, :destroy]
    end

    # devise_for :users
    #devise_for :users, :skip=>[:omniauth_callbacks, :sessions], :controllers => { :registrations => 'registrations'}
    post '/stories/update_story_read', to: 'stories#update_story_read', as: :update_story_read
    post '/stories/show_selected_stories', to: 'stories#show_selected_stories', as: :show_selected_stories

    get '/lists/:id/download', to: "api/v1/lists#download", as: :list_download

    resources 'illustrations' do
      get :autocomplete_user_email, :on => :collection
      get :autocomplete_tag_name, :on => :collection
    end

    #Organization_routes
    get '/organizations/organization_sign_up_model', to: 'organizations#organization_sign_up_model', as: :organization_sign_up_model
    post '/organizations/organization_sign_up', to: 'organizations#organization_sign_up', as: :organization_sign_up
    get '/organizations/new_users', to: 'organizations#new_users', as: :new_users
    get '/organizations/organizations_list', to: 'organizations#organizations_list', as: :organizations_list
    get 'organizations/assign_org_role', to: 'organizations#assign_org_role', as: :assign_org_role
    get '/organizations/check_org_publisher', to: 'organizations#check_org_publisher', as: :check_org_publisher
    post '/organizations/add_org_logo', to: 'organizations#add_org_logo', as: :add_org_logo
    #get '/organizations/remove_site_role', to: 'organizations#remove_site_role', as: :remove_site_role
    get '/organizations/validate_org_name_country', to: 'organizations#validate_org_name_country', as: :validate_org_name_country
    get '/organizations/autocomplete', to: 'organizations#autocomplete', as: :organizations_autocomplete
    get 'organizations/remove_org_role_dialog', to: 'organizations#remove_org_role_dialog', as: :remove_org_role_dialog
    get 'organizations/remove_org_role', to: 'organizations#remove_org_role', as: :remove_org_role

    get '/illustrations/:id/new_flag_illustration', to: 'illustrations#new_flag_illustration' , as: :new_flag_illustration
    post '/illustrations/flag_illustration/:id', to: 'illustrations#flag_illustration' , as: :flag_illustration

    get '/illustrations/download/:id', to: 'illustrations#download', as: :download_illustrations
    get '/illustration-view/:id', to: 'illustrations#illustration_view', as: :view_illustration
    post '/illustrations/update_favorites', to: 'illustrations#update_favorites', as: :update_favorites

    get '/stories/bulk_download', to: 'stories#bulk_download', as: :bulk_download
    #get '/stories/show_selected_stories', to: 'stories#show_selected_stories', as: :show_selected_stories

    resources 'stories',  except: [:show, :index] do
      resources 'pages' do
        get 'epub'
      end
      resources 'translations'
      resources 'relevels'
      member do
        patch 'publish'
        post 'create_post'
      end
      get :autocomplete_tag_name, :on => :collection
    end
    get 'profile/change_translator' => 'profile#change_translator', as: :profile_change_translator

    get "/stories/new_story_from_illustration/:id", to: "stories#new_story_from_illustration", as: :new_story_from_illustration
    get "/stories/create_story_from_illustration", to: "stories#create_story_from_illustration", as: :create_story_from_illustration
    get '/stories/:id/editable', to: 'stories#editable' , as: :story_editor_editable
    post '/stories/reviewer_rating_comment', to: 'stories#reviewer_rating_comment', as: :reviewer_rating_comment
    get '/stories/edit_story_editor/:id', to: 'stories#edit_story_editor', as: :edit_story_editor
    patch '/stories/:id/assign_change_editor', to: 'stories#assign_change_editor', as: :assign_change_editor
    get '/stories/close_assign_dailog/:id', to: 'stories#close_assign_dailog', as: :close_assign_dailog
    get '/stories/:id/new_flag_story', to: 'stories#new_flag_story' , as: :new_flag_story
    post '/stories/flag_story/:id', to: 'stories#flag_story' , as: :flag_story
    post "/stories/recommend_story_on_home", to: "stories#recommend_story_on_home", as: :recommend_story_on_home
    get '/stories/download-story/:id', to: 'stories#download_story', as: :download_story


    get 'stories/show-in-iframe/:id', to: 'stories#show_in_iframe', as: :v0_show_story_in_iframe
    get "/start" , to: 'home#index', as: :start_new_story
    get "/translate_suggestions" , to: 'stories#translate_suggestions' , as: :stories_translate_suggestions
    get 'stories/:id/story-review', to: 'stories#story_review', as: :story_review
    post 'stories/:id/reviewer-comments', to: "stories#reviewer_comments", as: :reviewer_comments
    get 'stories/review_next_story/:id', to: "stories#review_next_story", as: :review_next_story
    resources 'illustration_crops'

    # editor routes
    patch '/editor/:id/update_dummy_draft', to: "story_editor#update_dummy_draft", as: :update_dummy_draft
    get '/editor/story/user_email', to: 'story_editor#get_email', as: :story_editor_get_email
    get '/editor/story/:id', to: 'story_editor#story' , as: :story_editor
    get '/editor/illustration/:id', to: 'story_editor#illustration_for_crop' , as: :illustration_for_crop, :defaults => { :format => :json }
    post '/editor/:page_id/crop/:id', to: 'story_editor#crop_illustration' , as: :crop_illustration
    get '/editor/page/:id', to: 'story_editor#page_edit' , as: :page_edit
    put '/editor/page/:page_id/change_template/:id', to: 'story_editor#change_page_template' , as: :change_template
    put '/editor/story/:story_id/insert/:id', to: 'story_editor#insert_page' , as: :insert_page
    put '/editor/story/:story_id/duplicate/:id', to: 'story_editor#duplicate_page' , as: :duplicate_page
    delete '/editor/story/:story_id/delete/:id', to: 'story_editor#delete_page' , as: :delete_page
    post '/editor/page/:id/illustration', to: 'story_editor#update_page_illustration', as: :update_page_illustration
    get '/editor/page/:id/illustration', to: 'story_editor#remove_page_illustration', as: :remove_page_illustration
    post '/editor/page/:id/content', to: 'story_editor#update_page_content', as: :update_page_content
    post '/editor/page/:id/auto_save_content', to: 'story_editor#auto_save_content', as: :auto_save_content
    post '/editor/page/:id/save_content_on_blur', to: 'story_editor#save_content_on_blur', as: :save_content_on_blur
    post '/editor/story/:id/rearrange', to: 'story_editor#rearrange_page', as: :rearrange_page
    get '/editor/search/illustration', to: 'story_editor#search_illustration', as: :search_illustration
    get '/editor/new_illustration', to: 'story_editor#new_illustration', as: :editor_new_illustration
    post '/editor/create_illustration', to: 'story_editor#create_illustration', as: :editor_create_illustration
    get '/editor/story/:id/validate_pages', to: 'story_editor#validate_story_pages', as: :editor_validate_story_pages
    get '/editor/story/:id/publish', to: 'story_editor#publish_form', as: :editor_publish_story_form
    get '/editor/story/:id/edit_book_info', to: 'story_editor#edit_book_info', as: :editor_edit_book_info
    patch '/editor/story/:id/publish', to: 'story_editor#publish', as: :editor_publish_story
    patch '/editor/story/:id/update', to: 'story_editor#update', as: :editor_update_story
    patch '/editor/story/:id/update_book_info', to: 'story_editor#update_book_info', as: :editor_update_book_info
    get '/editor/autocomplete_user_email', to: 'story_editor#autocomplete_user_email', as: :autocomplete_user_email_path
    get '/editor/save_to_draft', to: 'story_editor#save_to_draft', as: :save_to_draft
    get '/editor/get-all-illustrations', to: 'story_editor#get_all_illustrations', as: :get_all_illustrations
    get '/editor/get-favourite-illustrations', to: 'story_editor#get_favourite_illustrations', as: :get_favourite_illustrations
    get '/editor/upload-illustration', to: 'story_editor#upload_illustration', as: :upload_illustration
    get '/editor/language_script', to: "story_editor#language_script", as: :story_language_script
    get "/editor/create", to: "stories#create_story", as: :create_story
    get "/editor/:story_id/translate", to: "translations#translate_story", as: :translate_story
    get "/editor/:story_id/relevel", to: "relevels#relevel_story", as: :relevel_story

    # illustration tags
    get '/illustration/edit-tags/:id', to: 'illustrations#edit_tags', as: :edit_illustration_tags
    patch '/illustration/:id/update-tags', to: 'illustrations#update_tags', as: :update_illustration_tags
    get 'illustration/:id/used_stories', to: 'illustrations#illustration_used_in_stories', as: :illustration_used_in_stories
    #contest routes
    get 'contests/:id/contest_winners_details', to: 'contests#contest_winners_details', as: :contest_winners_details
    resources :contests
    get '/contests/:id/details', to: 'contests#contest_details', as: :contest_details
    #contest_illustrations
    post '/illustrations/contest_image', to: 'illustrations#contest_image', as: :contest_image

spp-master/app/views/pages/_illustrator_links.erb
<% illustrators.each_with_index do | illustrator, index | %>
  <span><%= link_to illustrator, host_url+"/users/#{Person.find(illustrators_id[index]).try(:user).try(:slug)}"  %></span><% unless index == illustrators.length - 1  %>,<% end %>
<% end %>

spp-master/app/views/pages/_license.erb
<%
  if license == 'CC BY 4.0'
    image_src = asset_path_as_per_request_format('ccby.png')
  elsif license == 'CC BY 0'
    image_src = asset_path_as_per_request_format('cc0.png')
  else
    image_src = asset_path_as_per_request_format('publicdomain.svg')
  end
%>
<div class="cc_footer">
  	<div class="back_inner_page by_logo">
      <img src="<%= image_src %>"/>
    </div>
    <% if license == 'CC BY 4.0' %>
      <p>
      <%= t "spp.license.cc_by_4_html" %>
      </p>
    <% else %>
      <p>
        <%= t "spp.license.pd_html" %>
      </p>
    <% end %>
</div>

spp-master/app/views/pages/_navigate_to.html.erb
<a class="page-control previous-page" href="javascript:void(0);">
  <i class="fa fa-arrow-left"></i>
</a>
<% @story.pages.each_with_index do |page, index| %>
  	<%= render :partial=>"/pages/page", locals: {page: page} %>
<% end %>
<a class="page-control next-page" href="javascript:void(0);">
  <i class="fa fa-arrow-right animated shake"></i>
</a>
<script type="text/javascript">
  $(document).ready(pages_init);
  $(document).ready(setup_page_controls);
</script>

spp-master/app/views/pages/_page.html.erb
<div  id="<%= (page==@page)? 'selected_page':'' %>" class="<%= (page!=@page)? 'other-pages':'' %> page-container-<%= page.page_template.orientation %> story-page <%=page.story.language.script%>" >
  <div class='<%= page.page_template.name %> <%= page.illustration_crop.nil? ? '' : 'has_illustration' %> illustration'>
    <% if page.illustration_crop %>
      <% if illustration_crop_missing(page) %>
       <img src="<%= illustration_image_url(page) %>" style="<%= preview_illustration_crop_style(page) %>"/>
      <% else %>
      <img class='responsive_illustration'
        data-size1-src="<%= page.illustration_crop.url(:size1) %>"
        data-size2-src="<%= page.illustration_crop.url(:size2) %>"
        data-size3-src="<%= page.illustration_crop.url(:size3) %>"
        data-size4-src="<%= page.illustration_crop.url(:size4) %>"
        data-size5-src="<%= page.illustration_crop.url(:size5) %>"
        data-size6-src="<%= page.illustration_crop.url(:size6) %>"
        data-size7-src="<%= page.illustration_crop.url(:size7) %>"
        <% if @offline_processing %>
          src="image_<%= page.position %>.jpg"
        <% elsif (!size_to_render.nil? rescue false) %>
          src="<%= page.illustration_crop.image.url(size_to_render) %>"
        <% end %>
      />
     <% end %>
    <% end %>
  </div>
  <%= render :partial => page_partial(page, @offline_processing), locals: {page: page, story_read_id: @story_read_id} %>
</div>

spp-master/app/views/pages/_page_templates.html.erb
<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
  <% @template_options.each do |template| %>
    <li role="presentation">
      <a role="menuitem" href="#">
        <img src="/assets/story_page_templates/<%= template.name %>.png", width=100,height=100/>
     </a>
    </li>
<% end %>
</ul>

spp-master/app/views/pages/_photographer_links.erb
<% photographers.each_with_index do | photographer, index | %>
    <span><%= link_to photographer, host_url+"/users/#{photographers_slug[index]}"  %></span><% unless index == photographers.length - 1  %>,<% end %>
<% end %>

spp-master/app/views/pages/_recommend_another_story.html.erb
<div
  id="<%= (page==@page)? 'selected_page':'' %>"
  class="<%= (page!=@page)? 'other-pages':'' %> page-container-<%= page.page_template.orientation %> story-page recommended_page">
  <div class="top-section">
    <section class="carousel-thumbnail">
      <div class="row slider-carousel common-style">
        <label class="<%= page.page_template.orientation %>_back_to_story">Back to story page</label>
        <% if similar_stories.any? %>
          <h2>If you liked this, you will also like <i class="fa fa-circle"></i> <i class="fa fa-circle"></i> <i class="fa fa-circle"></i></h2>
          <div class="<%= page.page_template.orientation %>_recommended_story_container">
            <ul class="bxslider1 story-slides <%= page.page_template.orientation %>_recommended_story_ui">
              <% similar_stories.each do |story|%>
                <li>
                  <div class="carousel-img lands <%= page.page_template.orientation %>_recommended_image">
                  <a href="<%= react_stories_show_path(story.url_slug) %>" target="_blank"><img src="<%= story.image_url %>"></a>
                  </div>
                  <div class="carousel-content <%= page.page_template.orientation %>_recommended_carousal">  
                    <h3><a class="title" href="<%= react_stories_show_path(story.url_slug) %>" target="_blank"><%= story.title %></a></h3>
                     <h6><%= story.language %> | Reading Level <%= story.reading_level %></h6>
                  </div>  
                </li>
              <% end %>
              </ul>
            </div>
        <% end %>
      </div>
    </section>
</div>
</div>

spp-master/app/views/pages/_show.html.erb
<div class="modal fade" id="myModal" tabindex="-1"  role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="vertical-alignment-helper1 story_preview_page">
   <div class="modal-dialog <%= @page.page_template.orientation %> vertical-align-center1">
    <div class="modal-content <%= @story.language.script %> ">
        <span class="screen-mode">
          <a href="#"  onclick="fullscreen_read()" id="fullScreen"><img src="<%= asset_path("expand_icon_final.png")%>" alt="Go Full Screen" title="Go Full Screen" style="border: none; width: 22px; height: 22px;"/></a>
          <a href="#"  onclick="exit_full_screen()" id="exitFullScreen"><img src="<%= asset_path("minimise_icon_final.png")%>" alt="Exit Full Screen" title="Exit Full Screen" style="border: none; width: 22px; height: 22px;"/></a>
        </span>
      <button id="close-button" class="close close-reader" aria-hidden="true" data-dismiss="modal" type="button"><i class="fa fa-times-circle"></i></button>
      <div id="modal-body" class="modal-body">
        <div id="story-metadata" data-story-title="<%= @story.title %>" />
        <%= render "/pages/navigate_to" %>
      </div>
      <% if @disable_review_link == nil %>
        <%if (@story.status == "published" && @story.organization_id == nil) && ( current_user && current_user.is_language_reviewer(@story.language.name)) && (!@story.authors.include?(current_user)) %>
          <%if @story.flaggings_count == nil %>
            <%if @story.reviewer_comment.present?%>
              <div class="reviewed_story_<%= @story.orientation%>">
                <label>Story Reviewed</label>
              <div>
            <% else %>
              <div class="review_story_<%= @story.orientation%>">
                <%= link_to "Click here to start rating the story", story_review_path(@story, :flag => true), :method => :get, target: '_blank'%>
              </div>
            <% end %>
          <% else %>
              <div class="reviewed_story_<%= @story.orientation%>">
                <label>Flagged Story</label>
              <div>
          <% end %>
        <% end %>
      <%end%>
    </div>
   </div>
  </div>
 </div>
<script type="text/javascript">
  $(document).ready(pages_init);
  $(document).ready(screen_mode);
  $(document).ready(function(){
    var user_signed_in = "<%= session[:check_user_signed_in] %>";
    on_close_exit_full_screen(user_signed_in);
  });
  $(document).ready(activate_arrowkeys);
  </script>

spp-master/app/views/pages/_show_back_inner_cover_page.html.erb
<div class='<%= page.page_template.name %> content english'>
  <div class="attrb-full">
    <div class="attrib-logo">
      <img src="<%= asset_path_as_per_request_format('pb-storyweaver-logo-01.png') %>" />
    </div>
    <div class="attrib-synopsis">
      <p>
        This book was made possible by Pratham Books' StoryWeaver platform. Content under Creative Commons licenses can be downloaded, translated and can even be used to create new stories ­ provided you give appropriate credit, and indicate if changes were made. To know more about this, and the full terms of use and attribution, please visit the following <a href = "<%= host_url %>/terms_and_conditions" target="_blank">link</a>.
      </p>
    </div>
  </div>
  <div class="attribution-text">
    <div class="attribution-center">
      <%
        self_attribution = @story.attributions(page).select{|a| a.class == SelfAttribution}.first rescue nil
        parent_story_attribution = @story.attributions(page).select{|a| a.class == ParentStoryAttribution}.first rescue nil
        original_story_attribution = @story.attributions(page).select{|a| a.class == OriginalStoryAttribution}.first rescue nil
        illustration_attributions = @story.attributions(page).select{|a| a.class == IllustrationAttribution}
      %>
      <% unless self_attribution.nil? %>
        <p class="story-attribution-section">Story Attribution:</p>
        <span class="self-attribution">
          This story: <span class="<%= self_attribution.script %>"><%=self_attribution.title%></span> is <%= self_attribution.story_action_type %> by
          <%= render :partial => "pages/author_links", locals: {authors: self_attribution.authors}, :formats => [:html] %>.
          <% if self_attribution.is_original_story %>
          <%= render :partial => "pages/copyright_and_license", locals: {attribution: self_attribution}, :formats => [:html] %>
          <% else %>
            The © for this <%= self_attribution.derivation_type == 'translated' ? 'translation' : 're-level' %> lies with <%= self_attribution.copyright_holder %>, <%= self_attribution.copy_right_year %>. Some rights reserved. Released under <%= @story.license_type %> license.
          <% end %>
        </span>
      <%end%>
      <% unless parent_story_attribution.nil? %>
        <span class="parent-story-attribution">
          Derived from: <span class="<%= parent_story_attribution.script %>">'<%= link_to parent_story_attribution.title , host_url+"/stories/#{parent_story_attribution.url_slug}" %>'</span>, by
          <%= render :partial => "pages/author_links", locals: {authors: parent_story_attribution.authors}, :formats => [:html] %>.
          <%= render :partial => "pages/copyright_and_license", locals: {attribution: parent_story_attribution}, :formats => [:html] %>
        </span>
      <%end%>
      <% unless original_story_attribution.nil? %>
        <span class="original-story-attribution">
          Based on Original story: <span class="<%= original_story_attribution.script %>">'<%= link_to original_story_attribution.title , host_url+"/stories/#{original_story_attribution.url_slug}" %>'</span>, by
          <%= render :partial => "pages/author_links", locals: {authors: original_story_attribution.authors} %>.
          <%= render :partial => "pages/copyright_and_license", locals: {attribution: original_story_attribution } %>
        </span>
      <%end%>
      <% unless parent_story_attribution.nil? %>
        <span class="derived-story-text">
          This story may have intermediate versions between the root and parent story. To see all versions, please visit the links.
        </span>
      <%end%>
      <% unless self_attribution.nil? || @story.other_credits.blank? %>
        <p class="other-credits-section">Other Credits:</p>
        <span class="other-credits"><%= @story.other_credits %></span>
      <%end%>
      <p class="illustration-attributions-section">Images Attributions:</p>
      <% illustration_attributions.each do |attribution|  %>
        <span class="illustration-attribution">
          <%= attribution.page_number == 1 ? "Cover page" : "Page #{attribution.page_number}" %>:
          <%= link_to attribution.name, host_url+"/illustrations/#{attribution.url_slug}" %>, by
          <%= render :partial => "pages/illustrator_links", locals: {illustrators: attribution.illustrators, illustrators_id: attribution.illustrators_id} %><%= attribution.photographers.empty? ? '' : ',' %>
          <%= render :partial => "pages/photographer_links", locals: {photographers: attribution.photographers, photographers_slug: attribution.photographers_slug} %>
          <% if attribution.license_type == 'Public Domain' %>
            <%= attribution.photographers.empty? ? '' : ',' %><%= attribution.copy_right_year %>.
            Released under Public Domain Mark by <%=attribution.copyright_holders.join(', ')%>.
          <% else %>
            © <%=attribution.copyright_holders.join(', ')%>, 
            <%= attribution.copy_right_year %>. Some rights reserved. Released under <%=attribution.license_type %> license.
          <% end %>
        </span>
      <% end %>
    </div>
  </div>
  <div class="license_container">
    <div class="license_cont-middle">
      <span class="discl-txt">Disclaimer:<a href="<%= host_url %>/terms_and_conditions" target="_blank">https://www.storyweaver.org.in/terms_and_conditions</a> </span>
      <%= render :partial => "pages/license", locals: {license: @story.license_type } %>
      <% @additional_illustration_license_types.each do |license|  %>
        <%= render :partial => "pages/license", locals: {license: license} %>
      <% end %>
    </div>
		  <div class="donor-container">
				  <%= render :partial => "pages/donor", locals: {donor: @story.donor} if @story.donor%>
		  </div>
  </div>
</div>

spp-master/app/views/pages/_show_dedication_page.html.erb
<div class='<%= page.page_template.name %> content english'>
  <div class="attrb-full">
    <div class="attrib-logo">
      <img src="<%= asset_path_as_per_request_format('pb-storyweaver-logo-01.png') %>" />
    </div>
  </div>
		<div class="attribution-text">
    <div class="attribution-center">
				<p>
				  <strong>Created by</strong>
				  <%= @story.youngsters_of(page).map{|c| "#{c.name.capitalize} (#{c.age} years old)"}.join(", ")%>
						<% if @story.last_dedication_page(page) || (@story.youngsters && @story.youngsters.size == 1 && @story.youngsters.first.name != derivator_names(@story))%>
						  <span class="helped-authors">, with the help of </span><%= derivator_names(@story) %>.
				  <% end %>
				</p>
      <% if @story.last_dedication_page(page) %>
				    <span class="more-info"><%= @story.more_info %></span>
      <%end%>
    </div>
		</div>
  <div class="license_container">
    <img src="<%= asset_path_as_per_request_format('Bottom-SW-Logo.png') %>" />
  </div>
</div>

spp-master/app/views/pages/_story_page.html.erb
<h1>Create a Page</h1>

  <div class="container-fluid">
    <div class="row">
      <% @story_page_templates.each do |story_page_template|%>
        <div class="col-md-1 thumbnail page-template-preview">
            <%=link_to( image_tag("story_page_templates/" + story_page_template.name + ".png"),
                     story_page_template_path(story_page_template.id), remote: true) %>
        </div>
      <% end %>
    </div>
  </div>
  <div class='row'>
    <div class="col-md-7">
      <div id='selected_story_page_template' class='page-container'>
        <p>Select template</p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-5">
      <%= simple_form_for [@story, @page],url: story_pages_path(@story),html: { class: 'form-horizontal',  multipart: true } do |f| %>
        <%= f.association :page_template, collection: @story_page_templates, label_method: :name, value_method: :id %>
        <%= f.association :illustration, label_method: :name, value_method: :id %>
        <%= f.input :content %>
        <%= f.button :submit %>
      <% end %>
    </div>
  </div>

spp-master/app/views/pages/navigate_to.js.erb
$('#modal-body').html("<%= escape_javascript(render(:partial=>"navigate_to")) %>");

$('.modal-dialog').removeClass('portrait');
$('.modal-dialog').removeClass('landscape');
$('.modal-dialog').addClass('<%= @page.page_template.orientation %>');
$('#myModal').focus();

spp-master/app/views/pages/show.epub.erb
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html[<!ENTITY nbsp "&#160;">]>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<%= @story.language.locale %>" lang="<%= @story.language.locale %>">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <%= wicked_pdf_stylesheet_link_tag "language_fonts" -%>
    <%= wicked_pdf_stylesheet_link_tag "bootstrap3-wysihtml5-editor" -%>
    <%= wicked_pdf_stylesheet_link_tag "story_epub" -%>
    <%= render "pages/epub_fonts" %>
  </head>
  <body id="story_epub_body">
    <div id="story_epub">
      <div id="storyReader" class="<%= @story.language.script %>">
        <%= render :partial=>"pages/page", locals: {page: @page} %>
      </div>
    </div>
  </body>
</html>

spp-master/app/views/pages/show.pdf.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <%= wicked_pdf_stylesheet_link_tag "fonts" -%>
    <%= wicked_pdf_stylesheet_link_tag "language_fonts" -%>
    <%= wicked_pdf_stylesheet_link_tag "stories" -%>
    <%= wicked_pdf_stylesheet_link_tag "page" -%>
    <%= wicked_pdf_stylesheet_link_tag "bootstrap3-wysihtml5-editor" -%>
    <%= wicked_pdf_stylesheet_link_tag "story_pdf" -%>
  </head>
  <body class="pdf_body">
    <div id="story_pdf">
      <% @story.pages.each do |page| %>
        <div class="page <%= @story.language.script %>">
          <div class="page-container-<%= page.page_template.orientation %>">
            <div class='<%= page.page_template.name %> <%= page.illustration_crop.nil? ? '' : 'has_illustration' %> illustration'>
              <% unless page.illustration_crop.nil? %>
              <% debug = defined?(debug) ? debug : params[:debug].present? ? params[:debug] : false %>
              <% resolution = defined?(resolution) ? resolution : params[:high_resolution].present? ? "high" : "low" %>
              <%= debug.present? ?
                  image_tag(page.illustration_crop.image.url(resolution == "high" ? :original : :large)) :
                  wicked_pdf_image_tag_for_illustration_crops(page.illustration_crop.image.try(Settings.illustration.path, resolution == "high" ? :original : :large)) %>
              <% end %>
            </div>
            <% if page.page_template.name != "sp_h_text_overlay1" %>
              <span class="<%= page.page_template.name %> content-container">
                <%= render :partial => page_partial(page), locals: {page: page, story_read_id: nil} %>
              </span>
            <% else %>
              <%= render :partial => page_partial(page), locals: {page: page, story_read_id: nil} %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </body>
</html>