spp-master/config/routes.rb
Rails.application.routes.draw do
  root 'react#index'
  #Added v0 prefix to all rails routes
  #Rails routes blocking offline saving if no prefix
  scope :v0 do

    get "/blog" => "blog_posts#index", as: :v0_blog_posts
    post "/blog" => "blog_posts#create", as: :v0_create_blog_post
    get '/blog/search', to: 'blog_posts#search', as: :v0_blog_search
    get '/blog/dashboard', to: 'blog_posts#dashboard', as: :v0_blog_dashboard
    get '/blog/drafts', to: 'blog_posts#drafts', as: :v0_blog_drafts
    get '/blog/scheduled_posts', to: 'blog_posts#scheduled_posts', as: :v0_blog_scheduled_posts
    get '/blog/de_activated', to: 'blog_posts#de_activated', as: :v0_blog_de_activated
    get '/blog/new_comments', to: 'blog_posts#new_comments', as: :v0_new_comments
    resources :blog_posts,  except: [:create, :index] do
      get :autocomplete_tag_name, :on => :collection
      resources :comments, only: [:create, :destroy]
    end

    # devise_for :users
    #devise_for :users, :skip=>[:omniauth_callbacks, :sessions], :controllers => { :registrations => 'registrations'}
    post '/stories/update_story_read', to: 'stories#update_story_read', as: :update_story_read
    post '/stories/show_selected_stories', to: 'stories#show_selected_stories', as: :show_selected_stories

    get '/lists/:id/download', to: "api/v1/lists#download", as: :list_download

    resources 'illustrations' do
      get :autocomplete_user_email, :on => :collection
      get :autocomplete_tag_name, :on => :collection
    end

    #Organization_routes
    get '/organizations/organization_sign_up_model', to: 'organizations#organization_sign_up_model', as: :organization_sign_up_model
    post '/organizations/organization_sign_up', to: 'organizations#organization_sign_up', as: :organization_sign_up
    get '/organizations/new_users', to: 'organizations#new_users', as: :new_users
    get '/organizations/organizations_list', to: 'organizations#organizations_list', as: :organizations_list
    get 'organizations/assign_org_role', to: 'organizations#assign_org_role', as: :assign_org_role
    get '/organizations/check_org_publisher', to: 'organizations#check_org_publisher', as: :check_org_publisher
    post '/organizations/add_org_logo', to: 'organizations#add_org_logo', as: :add_org_logo
    #get '/organizations/remove_site_role', to: 'organizations#remove_site_role', as: :remove_site_role
    get '/organizations/validate_org_name_country', to: 'organizations#validate_org_name_country', as: :validate_org_name_country
    get '/organizations/autocomplete', to: 'organizations#autocomplete', as: :organizations_autocomplete
    get 'organizations/remove_org_role_dialog', to: 'organizations#remove_org_role_dialog', as: :remove_org_role_dialog
    get 'organizations/remove_org_role', to: 'organizations#remove_org_role', as: :remove_org_role

    get '/illustrations/:id/new_flag_illustration', to: 'illustrations#new_flag_illustration' , as: :new_flag_illustration
    post '/illustrations/flag_illustration/:id', to: 'illustrations#flag_illustration' , as: :flag_illustration

    get '/illustrations/download/:id', to: 'illustrations#download', as: :download_illustrations
    get '/illustration-view/:id', to: 'illustrations#illustration_view', as: :view_illustration
    post '/illustrations/update_favorites', to: 'illustrations#update_favorites', as: :update_favorites

    get '/stories/bulk_download', to: 'stories#bulk_download', as: :bulk_download
    #get '/stories/show_selected_stories', to: 'stories#show_selected_stories', as: :show_selected_stories

    resources 'stories',  except: [:show, :index] do
      resources 'pages' do
        get 'epub'
      end
      resources 'translations'
      resources 'relevels'
      member do
        patch 'publish'
        post 'create_post'
      end
      get :autocomplete_tag_name, :on => :collection
    end
    get 'profile/change_translator' => 'profile#change_translator', as: :profile_change_translator

    get "/stories/new_story_from_illustration/:id", to: "stories#new_story_from_illustration", as: :new_story_from_illustration
    get "/stories/create_story_from_illustration", to: "stories#create_story_from_illustration", as: :create_story_from_illustration
    get '/stories/:id/editable', to: 'stories#editable' , as: :story_editor_editable
    post '/stories/reviewer_rating_comment', to: 'stories#reviewer_rating_comment', as: :reviewer_rating_comment
    get '/stories/edit_story_editor/:id', to: 'stories#edit_story_editor', as: :edit_story_editor
    patch '/stories/:id/assign_change_editor', to: 'stories#assign_change_editor', as: :assign_change_editor
    get '/stories/close_assign_dailog/:id', to: 'stories#close_assign_dailog', as: :close_assign_dailog
    get '/stories/:id/new_flag_story', to: 'stories#new_flag_story' , as: :new_flag_story
    post '/stories/flag_story/:id', to: 'stories#flag_story' , as: :flag_story
    post "/stories/recommend_story_on_home", to: "stories#recommend_story_on_home", as: :recommend_story_on_home
    get '/stories/download-story/:id', to: 'stories#download_story', as: :download_story


    get 'stories/show-in-iframe/:id', to: 'stories#show_in_iframe', as: :v0_show_story_in_iframe
    get "/start" , to: 'home#index', as: :start_new_story
    get "/translate_suggestions" , to: 'stories#translate_suggestions' , as: :stories_translate_suggestions
    get 'stories/:id/story-review', to: 'stories#story_review', as: :story_review
    post 'stories/:id/reviewer-comments', to: "stories#reviewer_comments", as: :reviewer_comments
    get 'stories/review_next_story/:id', to: "stories#review_next_story", as: :review_next_story
    resources 'illustration_crops'

    # editor routes
    patch '/editor/:id/update_dummy_draft', to: "story_editor#update_dummy_draft", as: :update_dummy_draft
    get '/editor/story/user_email', to: 'story_editor#get_email', as: :story_editor_get_email
    get '/editor/story/:id', to: 'story_editor#story' , as: :story_editor
    get '/editor/illustration/:id', to: 'story_editor#illustration_for_crop' , as: :illustration_for_crop, :defaults => { :format => :json }
    post '/editor/:page_id/crop/:id', to: 'story_editor#crop_illustration' , as: :crop_illustration
    get '/editor/page/:id', to: 'story_editor#page_edit' , as: :page_edit
    put '/editor/page/:page_id/change_template/:id', to: 'story_editor#change_page_template' , as: :change_template
    put '/editor/story/:story_id/insert/:id', to: 'story_editor#insert_page' , as: :insert_page
    put '/editor/story/:story_id/duplicate/:id', to: 'story_editor#duplicate_page' , as: :duplicate_page
    delete '/editor/story/:story_id/delete/:id', to: 'story_editor#delete_page' , as: :delete_page
    post '/editor/page/:id/illustration', to: 'story_editor#update_page_illustration', as: :update_page_illustration
    get '/editor/page/:id/illustration', to: 'story_editor#remove_page_illustration', as: :remove_page_illustration
    post '/editor/page/:id/content', to: 'story_editor#update_page_content', as: :update_page_content
    post '/editor/page/:id/auto_save_content', to: 'story_editor#auto_save_content', as: :auto_save_content
    post '/editor/page/:id/save_content_on_blur', to: 'story_editor#save_content_on_blur', as: :save_content_on_blur
    post '/editor/story/:id/rearrange', to: 'story_editor#rearrange_page', as: :rearrange_page
    get '/editor/search/illustration', to: 'story_editor#search_illustration', as: :search_illustration
    get '/editor/new_illustration', to: 'story_editor#new_illustration', as: :editor_new_illustration
    post '/editor/create_illustration', to: 'story_editor#create_illustration', as: :editor_create_illustration
    get '/editor/story/:id/validate_pages', to: 'story_editor#validate_story_pages', as: :editor_validate_story_pages
    get '/editor/story/:id/publish', to: 'story_editor#publish_form', as: :editor_publish_story_form
    get '/editor/story/:id/edit_book_info', to: 'story_editor#edit_book_info', as: :editor_edit_book_info
    patch '/editor/story/:id/publish', to: 'story_editor#publish', as: :editor_publish_story
    patch '/editor/story/:id/update', to: 'story_editor#update', as: :editor_update_story
    patch '/editor/story/:id/update_book_info', to: 'story_editor#update_book_info', as: :editor_update_book_info
    get '/editor/autocomplete_user_email', to: 'story_editor#autocomplete_user_email', as: :autocomplete_user_email_path
    get '/editor/save_to_draft', to: 'story_editor#save_to_draft', as: :save_to_draft
    get '/editor/get-all-illustrations', to: 'story_editor#get_all_illustrations', as: :get_all_illustrations
    get '/editor/get-favourite-illustrations', to: 'story_editor#get_favourite_illustrations', as: :get_favourite_illustrations
    get '/editor/upload-illustration', to: 'story_editor#upload_illustration', as: :upload_illustration
    get '/editor/language_script', to: "story_editor#language_script", as: :story_language_script
    get "/editor/create", to: "stories#create_story", as: :create_story
    get "/editor/:story_id/translate", to: "translations#translate_story", as: :translate_story
    get "/editor/:story_id/relevel", to: "relevels#relevel_story", as: :relevel_story

    # illustration tags
    get '/illustration/edit-tags/:id', to: 'illustrations#edit_tags', as: :edit_illustration_tags
    patch '/illustration/:id/update-tags', to: 'illustrations#update_tags', as: :update_illustration_tags
    get 'illustration/:id/used_stories', to: 'illustrations#illustration_used_in_stories', as: :illustration_used_in_stories
    #contest routes
    get 'contests/:id/contest_winners_details', to: 'contests#contest_winners_details', as: :contest_winners_details
    resources :contests
    get '/contests/:id/details', to: 'contests#contest_details', as: :contest_details
    #contest_illustrations
    post '/illustrations/contest_image', to: 'illustrations#contest_image', as: :contest_image

spp-master/app/controllers/api/v1/organizations_controller.rb
class Api::V1::OrganizationsController < Api::V1::ApplicationController

  respond_to :json
def autocomplete
    organizations = Organization.search(params[:query], {
                                             fields: ["organization_name^5"],
                                             match: :word_start,
                                             limit: 10,
                                             load: false,
                                             misspellings: {below: 5}
                                           })
     results = {}
     organizations.each do |org|
       results[:id] = org.id
       results[:name] = org.organization_name
       results[:country] = org.country
       results[:city] = org.city
       results[:children] = org.children_impacted
       results[:classrooms] = org.number_of_classrooms
     end 
     
    render json: {"ok" => true, :data => [results]} 
  end
end

spp-master/app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  #autocomplete :organization, :organization_name
  before_action :authenticate_user!, :except => [:autocomplete, :validate_org_name_country] 

  def organization_sign_up_model
    @organization = Organization.new
  end

  def organization_sign_up
    @organization = Organization.where(:organization_name => params[:organization][:organization_name], :country => params[:organization][:country]).first
    unless @organization.present?
      @organization = Organization.new(organization_params)
      if @organization.save
        org_translation = @organization.translations.try(:first)
        org_translation.translated_name = @organization.organization_name
        org_translation.save!
        save_org_user(@organization)
      else
        flash.now[:error] = @organization.errors.full_messages.join(", ")
        respond_to do |format|
          format.js{ render "organization_sign_up_model" }
        end
      end
    else
      save_org_user(@organization)
    end
  end

  def save_org_user(organization)
    @user = User.find(current_user)
    @user.update_attributes(:organization_id =>  organization.id, :org_registration_date => DateTime.now, :city => organization.city)
    @user.save
    flash[:notice] = "You are now signed in as an organisational user. You can download multiple books in multiple formats in one click."
    content_managers=User.content_manager.collect(&:email).join(",")
    UserMailer.delay(:queue=>"mailer").organization_user_signup(content_managers,organization,current_user)
    respond_to do |format|
      format.js {render js: "window.location = '#{react_search_path(:bulk_download => true)}'"}
    end
  end

  def assign_org_role
    @user = User.find_by_id(params[:user_id])
    @org = Organization.find_by_id(@user.organization_id)
    if @org.organization_type == nil
      if params[:role] != "publisher"
        update_org_user(@user,params[:role])
        @org.status = "Approved"
        @org.organization_type = "Educator"
        @org.save!
        respond_to do |format|
          format.js{ render js: "window.location = '#{roles_path}';" }
          format.html{ redirect_to roles_path }
        end
      end
    else
      check_org_user(@user,params[:role])
    end
  end

  def update_org_user(user,role)
    user.update_role(role)
    flash[:notice] = "#{user.first_name} is assigned as "+role+" for "+ user.organization.organization_name
  end

  def check_org_user(user,role)
    if user.organization_roles != nil && user.organization_roles.include?(role)
      role = params[:role] == "admin"? "an admin" : "a publisher" 
      flash[:error] = "#{user.first_name} is already "+role+" for "+user.organization.organization_name
      respond_to do |format|
        format.js{ render js: "window.location = '#{roles_path}';" }
        format.html{ redirect_to roles_path }
      end
    else
      if role == "admin"
        update_org_user(user,role)
        respond_to do |format|
          format.js{ render js: "window.location = '#{roles_path}';" }
          format.html{ redirect_to roles_path }
        end
      else
        if user.organization.organization_type != "Publisher"
          render :assign_org_role
        else
          update_org_user(user,role)
          respond_to do |format|
            format.js{ render js: "window.location = '#{roles_path}';" }
            format.html{ redirect_to roles_path }
          end
        end
      end
    end
  end

  def add_org_logo
    @user = User.find_by_id(params[:user][:id])
    @org = Organization.find_by_id(params[:organization][:id])
    if params[:org] && params[:org][:logo].present?
      @org.status = "Approved"
      @org.logo = params[:org][:logo]
      @org.organization_type = "Publisher"
      @org.save!
      update_org_user(@user,"publisher")
      respond_to do |format|
        format.js{ render js: "window.location = '#{roles_path}';" }
      end
    else
      @org.errors[:base] << "Logo can't be blank."
      render :assign_org_role
    end
  end

  def remove_org_role_dialog
    @user = User.find_by_id(params[:user_id])
    @org = @user.organization
    @role = params[:role]
    @site_role = params[:site_role]
  end

  def remove_org_role
    user = User.find_by_id(params[:user_id])
    roles = user.organization_roles.split(",")
    user.organization_roles = remove_roles(roles, params[:role])
    user.save!
    respond_to do |format|
      format.js{ render js: "window.location = '#{roles_path}';" }
    end
    flash[:notice] = user.first_name+" is successfully removed as "+ params[:role] +" for "+ user.organization.organization_name
  end

  def remove_site_role
    user = User.find_by_id(params[:user_id])
    user.update_attributes(:role => User.roles[:user])
    user.save!
    respond_to do |format|
      format.js{ render js: "window.location = '#{roles_path}';" }
    end
    flash[:notice] = user.first_name+" is successfully removed as "+ params[:role]
  end

  def remove_roles(user_roles, remove_role)
    if user_roles.length > 1
      return remove_role == "admin" ? "publisher" : "admin"
    else
      user_roles.delete(params[:role])
      return nil
    end
  end

  def validate_org_name_country
    organization = Organization.where(:organization_name => params[:org_name], :country => params[:country]).first
    render json: {"org_present" => organization.present? ? "true" : "false", "org" => organization}
  end

  def autocomplete
    render json: Organization.search(params[:query], {
                                             fields: ["organization_name^5"],
                                             match: :word_start,
                                             limit: 10,
                                             load: false,
                                             misspellings: {below: 5}
                                           }).map{|u| "#{u.organization_name}"}.uniq
  end

private
def organization_params
  params.require(:organization).permit(:organization_name,:organization_type, :country, :city, :number_of_classrooms, :children_impacted, :status)
  end
end

spp-master/app/views/organizations/_assign_org_role.html.erb
<div class="modal fade" id="assignRoleModal" tabindex="-1" role="dialog" aria-labelledby="moreLinksModalLabel" aria-hidden="true">
  <div class="modal-dialog" >
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h2 class="modal-title text-left">Add image to <%= org.organization_name %></h2>
      </div>
      <div class="modal-body modal-body-app">
        <div class="row setroles">
          <div class="col-md-12 col-sm-12">
            <% if org.errors.count != 0 %>
            <div class="alert alert-danger">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <div id="flash_error"><%= org.errors.full_messages.join(", ") %></div>
            </div>
            <% end %>
            <%= simple_form_for :org ,:url => add_org_logo_path, html: { multipart: true, id: "logo_form" }, :authenticity_token => true do |f| %>
            <%= f.file_field :logo, :id=> "logo", as: :file , :class => "user_logo" %>
            <input  name="organization[id]"  value ="<%= org.id %>" class="hidden"/>
            <input  name="user[id]"  value ="<%= user.id %>" class="hidden"/>
            <%= submit_tag "Submit" , :class => "btn btn-success" %>
            <% end %>
          </div>
        </div>
      </div>
      <!-- /modal-body -->
      <div class="modal-footer">
        <p id="validated_selected"> Please select atleast one story for download.</p>
        <div class="row row-gutter">
          <div class="text-right footer-container">
            <span class="gutter-sm-x vertical-i-top spacing-half-v">
            <span class="btn btn-app btn-brand-1" class="close" data-dismiss="modal" aria-label="Close">Cancel</span>
            </span>
          </div>
        </div>
      </div>
      <!-- /modal-footer -->
    </div>
    <!-- /modal-content -->
  </div>
  <!-- /modal-dialog -->
</div>
<script type="text/javascript">
  $('#logo_form').ajaxForm({
            dataType:  'script'
        });
</script>

spp-master/app/views/organizations/_remove_org_role_dialog.html.erb
<div>
<% if site_role == "true" %>
  Want to remove "<%= user.first_name %>" as a <%= role %>?
<% else %>
  Want to remove "<%= user.first_name %>" as a <%= role %> for "<%= org.organization_name %>" organization?
<% end %>
</div>

<script> 
  <% if site_role == "true" %>
   var url_link = "<%= remove_site_role_path %>"
  <% else %>
    var url_link = "<%= remove_org_role_path %>"
  <% end %>
  $('#remove_org_role_dialog').dialog({
    autoOpen: true,
    title: "Remove role",
    width: 400,
    modal: true,
    buttons : {
      "Ok" : function() {
        $.ajax({
          type: 'GET',
          dataType: 'script',
          url: url_link,
          data: {
            role: "<%= role %>",
            user_id: "<%= user.id %>"
          }
        });
      },
      "Cancel" : function() {
        $(this).dialog("close");
      }
    },
    dialogClass: 'change_orientation_dialog'
  })
</script>

spp-master/app/views/organizations/_show_org_sign_up.html.erb
<div class="modal-dialog modal-md bulk-download-signup" role="document">
  <div class="modal-content">
    <div class="modal-body modal-body-app">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <div class="form-group">
        <div class="spacing-half-v"></div>
        <div class="heading-title">Welcome to StoryWeaver!</div>
        <div class="spacing-half-v"></div>
      </div>
      <% if @organization.errors.count != 0 %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <div id="flash_error"><%= @organization.errors.full_messages.join(", ") %></div>
      </div>
      <% end %>
      <div class="row row-gutter">
        <div class="col-sm-12">
          <label class="big-margin-bottom">Please do take a few minutes to share some additional information about yourself.</label>
        </div>
        <%= simple_form_for organization, :url => organization_sign_up_path, :method => :post, :remote => true do |f| %>
        <div class="form-group form-group-lg-pad">
          <label class="heading-section label-required">Name of the Organisation</label>
          <%= f.input :organization_name,:label => false,:error => false,:input_html => { class: "form-control input-brand input-brand--lg"} %>
        </div>
        <div id="organization_autofill">
          <div class="form-group form-group-lg-pad">
            <label class="heading-section label-required">Country name</label>
            <%= f.collection_select(:country, { }, :id, :name, { :prompt => 'Select Country' }, {:class => 'country', :style => "width: 100%;"}) %>
          </div>
          <div class="form-group form-group-lg-pad">
            <label class="heading-section label-required">Number of classrooms</label>
            <%= f.input :number_of_classrooms,:label => false,:error => false,:input_html => { class: "form-control input-brand input-brand--lg", min: '1'} %>
          </div>
          <div class="form-group form-group-lg-pad">
            <label class="heading-section label-required">Number of children impacted (approximately)</label>
            <%= f.input :children_impacted,:label => false,:error => false,:input_html => { class: "form-control input-brand input-brand--lg", min: '1'} %>
            <input  name="organization[status]"  value ="New" class="hidden"/>
          </div>
        </div>
        <div class="form-group form-group-lg-pad">
          <label class="heading-section">Which states/cities are you working in?</label>
          <input  name="organization[city]" class="form-control input-brand input-brand--lg"/>
        </div>
        <div class="col-sm-12 text-right">
          <span class="gutter-sm-x vertical-i-top spacing-half-v">
          <%= f.submit "Submit", class: "btn btn-app btn-brand-1" %>
          </span>
          <span class="gutter-sm-x vertical-i-top spacing-half-v">
          <button type="button" class="btn btn-app btn-brand-1" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">Cancel</span></button>
          </span>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  $('#organization_organization_name').autocomplete({
    source: function( request, response ) {
      $.ajax({
        url: "<%= organizations_autocomplete_path%>",
        dataType: "json",
        data: {
          query: request.term
        },
        success: function( data ) {
          response(data);
        }
      });
    }
  });

  $('.country').on('change', function(){
    $.ajax({
      url: "<%= validate_org_name_country_path %>",
      dataType: "json",
      data: {
        org_name: $( "#organization_organization_name" ).val(),
        country: $(this).find("option:selected").val()
      },
      success: function( data ) {
        if(data.org_present == "true"){
          $('#organization_number_of_classrooms').val(data.org.number_of_classrooms);
          $('#organization_children_impacted').val(data.org.children_impacted);
          $("#organization_autofill *").children().prop('readonly',true);
        }else{
          $('#organization_number_of_classrooms').val("")
          $('#organization_children_impacted').val("")
        }
        response(data);
      }
    });
  });

  $('#organization_organization_name').keyup('change', function() {
    $('#organization_city, #organization_number_of_classrooms, #organization_children_impacted').val("")
    $('.country').selectpicker('val', "");
    $("#organization_autofill *").children().prop('readonly',false);
    $('.country').find('.selectpicker').attr('disabled',false)
  })
</script>

spp-master/app/views/organizations/add_org_logo.js.erb
$('#check_org_publisher_modal').html("<%= escape_javascript(render :partial => "assign_org_role", :locals => {:user => @user, :org => @org}) %>");
$('#assignRoleModal').modal("show");
$(document).ready(function () {
  $("#cancel").click(function () {
    $('#assignRoleModal').modal('hide');
  })
});

spp-master/app/views/organizations/assign_org_role.js.erb
$('#check_org_publisher_modal').html("<%= escape_javascript(render :partial => "assign_org_role", :locals => {:user => @user, :org => @org}) %>");
$('#assignRoleModal').modal("show");
$(document).ready(function() {
  $("#cancel").click(function(){
    $('#assignRoleModal').modal('hide');
  })
});

spp-master/app/views/organizations/organization_sign_up_model.js.erb
$('#organization_signup_model').html("<%= escape_javascript(render :partial => "show_org_sign_up", :locals => {:organization => @organization}) %>");
$(document).ready(function () {
  setTimeout(function () {
    if ($('.modal-open').length === 0) {
      $('body').addClass('modal-open')
    }
    $('#organization_signup_model').modal({
      show: true
    })
  }, 1000);

  <% if @organization.errors.count > 0 %>
      $(".country").append('<option>' + "<%= @organization.country.blank? ? 'Select Country' : @organization.country %>" + '</option>');
  <% end %>
  
  function myFunction() {
    var data = getCountryData();
    $.each(data, function(index,country) {
      $(".country").append('<option id='+ country.iso2 + '>' + country.countryname + '</option>');
    });
    $('.country').selectpicker({ liveSearch:true });
  }
  myFunction();
  <% if @organization.errors.count > 0 %>
      $('.country').selectpicker('val', "<%= @organization.present? ? @organization.country : '' %>");
  <% end %>
});

spp-master/app/views/organizations/remove_org_role_dialog.js.erb
$("#remove_org_role_dialog").html("<%= escape_javascript(render :partial=> "remove_org_role_dialog", :locals => {:user => @user, :org => @org, :role => @role, :site_role => @site_role}) %>");